---

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: pretty-format-json
        args: [--autofix]
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: no-commit-to-branch
        args: [--branch, master]
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.27.1
    hooks:
      - id: yamllint
  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3
  # - repo: https://gitlab.com/pycqa/flake8
  #   rev: 5.0.4
  #   hooks:
  #     - id: flake8
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, chore]
